#!/usr/bin/env ksh
#
#  @(#)fs615/db/ora/rman/linux/rh/usfs_local_sids, ora, build6_1, build6_1a,1.2:10/3/11:10:35:48
#  VERSION:  1.3
#  DATE:  10/3/11:10:35:48
# 
# Purpose:  List instance names on local host.
#
# Attention: Test any changes in bash, pdksh, and ksh93.
#
# Requires:
#    /etc/oratab
# Results:
#    Found ORACLE_SIDs are echoed to stdout
# 
# Suggested client invocation:   SIDS=$(fs_local_sids)

TAB=$(echo -e "\t")
# Turn off shell history subsititution for exclamation point
ps $$ | grep -q bash && set +H

export FS615_ORATAB=/etc/oratab
[[ $(uname) == "SunOS" ]] && export FS615_ORATAB=/var/opt/oracle/oratab

# Check for local host being a RAC server
INSTNBR=$( ps -ef | sed "/asm_pmon_+AS[M]/!d;s|.*asm_pmon_+AS[M]||" )
if [[ -z "$INSTNBR" ]]; then
   INSTNBR=$( sed "/^[ $TAB]*#/d; /^+ASM[0-9]:/!d; s|+ASM\([0-9]*\):.*|\1|" $FS615_ORATAB)
fi
if [[ -n "$INSTNBR" ]]; then
   # This server is a RAC node
   # It is an error if a dbname ends with a numeral in oratab
   SIDS=$(cat $FS615_ORATAB | egrep -v "^[  ]*$|^#|^\+|ASM|\*|MGMTDB" | cut -f1 -d: | \
      sed "s|$|$INSTNBR|")
else
   # This server is a Stand-Alone server
   SIDS=$(cat $FS615_ORATAB | egrep -v "^[  ]*$|^#|^\+|ASM|\*|MGMTDB" | cut -f1 -d:)
fi
# Set $SID_EXCLUDE_LIST 
eval $(sed "/^[ $TAB]*#/d; /export  *SID_EXCLUDE_LIST=/!d" /home/oracle/system/rman/rman_parameters.sh)
if [[ -n "$SID_EXCLUDE_LIST" ]]; then 
   SIDS=$(echo "$SIDS" | egrep -v "$SID_EXCLUDE_LIST")
fi
echo "$SIDS"
